name: Testing

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: P${{ matrix.php-versions }} - ${{ matrix.dependency-version }}
    strategy:
      matrix:
        php-versions: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run test suite
        run: composer test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3